name: ETH to T1 Bridge

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch:    # Hỗ trợ chạy thủ công

jobs:
  bridge:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Upload wallets.txt
        run: echo "${{ secrets.WALLETS_TXT }}" > wallets.txt
      
      - name: Run Bridge Script
        env:
          BRIDGE_CONTRACT_ADDRESS: ${{ secrets.BRIDGE_CONTRACT_ADDRESS }}
          AMOUNT_TO_BRIDGE: ${{ secrets.AMOUNT_TO_BRIDGE }}
        run: npm start
